// export const className: string[] = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', '', '', '', '', '',]
export const secondMenuClassName = {
  8: 's-eight',
  9: 's-nine',
  10: 's-ten',
  12: 's-twelve',
  13: 's-thirteen',

  17: 's-seventeen',
  18: 's-eighteen',
  19: 's-nineteen',
  20: 's-twenty',
  21: 's-twentyone',
  22: 's-twentytwo',
  23: 's-twentythree',
  24: 's-twentyfour',
  25: 's-twentyfive',
  26: 's-twentysix',
  27: 's-twentyseven',
  28: 's-twentyeight',
  29: 's-twentynine',
  30: 's-thirty',

  31: 's-thirtyone',
  32: 's-thirtytwo',
  33: 's-thirtythree',
  34: 's-thirtyfour',
  36: 's-thirtysix',
  37: 's-thirtyseven',

  38: 's-thirtyeight',
  39: 's-thirtynine',
  40: 's-fourty',
  41: 's-fourtyone',
  42: 's-fourtytwo',
  43: 's-fourtythree',
  44: 's-fourtyfour',
  45: 's-fourtyfive',
  46: 's-fourtysix',
  47: 's-fourtyseven',
  48: 's-fourtyeight',
  49: 's-fourtynine',
  50: 's-fifty',
  51: 's-fiftyone',
  52: 's-fiftytwo',
  53:'s-fiftythree',
  54:'s-fiftyfour',
  55:'s-fiftyfive',
  59:'s-fiftynine',
  56:'s-fiftysix',
  57:'s-fiftyseven',
  58:'s-fiftyeight',
}
export const thridMenuClassName = {
  1: 't-one',
  2: 't-two',
  3: 't-three',
  4: 't-four',
  5: 't-five',
  6: 't-six',
  7: 't-seven',
  8: 't-eight',
  9: 't-nine',
  10: 't-ten',
  11: 't-eleven',
  12: 't-twelve',
  13: 't-thirteen',
  14: 't-fourteen',
  15: 't-fifteen',
  16: 't-sixteen',
  17: 't-seventeen',
}