export default {
  //地址灾害隐患点
  geologicalDisasterPoint:[
    {
      prop:'name',
      label:'灾害点名称',
      width:'200',
      align:'',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'100',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'联系电话',
      width:'140',
      align:'center',
    },
    {
      prop:'type',
      label:'灾害点类型',
      width:'130',
      align:'center',
    },
    {
      prop:'scale',
      label:'规模',
      width:'80',
      align:'center',
    },
    {
      prop:'stability',
      label:'稳定性',
      width:'80',
      align:'center',
    },
    {
      prop:'risk',
      label:'风险大小',
      width:'80',
      align:'center',
    },
    {
      prop:'factor',
      label:'产生因素',
      width:'80',
      align:'',
    },
    {
      prop:'people',
      label:'受害人数',
      width:'80',
      align:'center',
    },
    {
      prop:'gdp',
      label:'经济损失(万元)',
      width:'80',
      align:'center',
    },
    {
      prop:'measure',
      label:'采取措施',
      width:'280',
      align:'',
    },
    {
      prop:'level',
      label:'灾害等级',
      width:'80',
      align:'center',
    },
    {
      prop:'address',
      label:'灾害地址',
      width:'130',
      align:'',
    },
    {
      prop:'detail',
      label:'详细',
      width:'140',
      align:'',
    },
  ],
  //地质灾害预警状态
  geologicalDisasterState:[
      {
        prop:'name',
        label:'灾害点名称',
        width:'250',
        align:'center',
      },
      {
        prop:'type',
        label:'灾害点类型',
        width:'100',
        align:'center',
      },
     {
        prop:'lon',
        label:'经度',
        width:'80',
        align:'center',
      },
     {
        prop:'lat',
        label:'纬度',
        width:'80',
        align:'center',
      },
      {
        prop:'ddatetime',
        label:'预警时间',
        width:'120',
        align:'center',
      },
      {
        prop:'level',
        label:'预警等级',
        width:'80',
        align:'center',
      },
    {
      prop:'cause',
      label:'预警类型',
      width:'140',
      align:'center',
    },
      {
        prop:'address',
        label:'灾害地址',
        width:'',
        align:'left',
      },
  ],
  //地质灾害预警报告
  geologicalDisasterReport: [
    {
      prop:'dataTime',
      label:'生成时间',
      width:'150',
      align:'center',
    },
    {
      prop:'fileName',
      label:'报告名称',
      width:'',
      align:'center',
    },
  ],
  //山洪预警状态
  mountainTorrentsState:[
    {
      prop:'name',
      label:'站点',
      width:'200',
      align:'center'
    },
    {
      prop:'type',
      label:'类型',
      width:'80',
      align:'center'
    },
    {
      prop:'lon',
      label:'经度',
      width:'70',
      align:'center'
    },
    {
      prop:'lat',
      label:'纬度',
      width:'70',
      align:'center'
    },
    {
      prop:'ddatetime',
      label:'时间',
      width:'140',
      align:'center'
    },
    {
      prop:'waterlevel',
      label:'当前水位(米)',
      width:'100',
      align:'center'
    },
    {
      prop:'alertlevel',
      label:'警戒水位(米)',
      width:'100',
      align:'center'
    },
    {
      prop:'cause',
      label:'预警原因',
      width:'',
      align:''
    },
  ],
  //山洪预警报告
  mountainTorrentsReport:[
    {
      prop:'dataTime',
      label:'生成时间',
      width:'200',
      align:'center'
    },
    {
      prop:'fileName',
      label:'报告名称',
      width:'',
      align:'center'
    },
  ],
  //山洪水库
  reservoir:[
    {
      prop:'VF01015_CN',
      label:'水库名称',
      width:'',
      align:'center'
    },
    {
      prop:'V06001',
      label:'经度',
      width:'',
      align:'center'
    },
    {
      prop:'V05001',
      label:'纬度',
      width:'',
      align:'center'
    },
    {
      prop:'V_COUNTY',
      label:'城市',
      width:'',
      align:'center'
    },
    {
      prop:'V_ADDRESS',
      label:'水库地址',
      width:'',
      align:'center'
    },
    {
      prop:'DDATETIME',
      label:'预警时间',
      width:'',
      align:'center'
    },
    {
      prop:'RZ',
      label:'当前水位(米)',
      width:'',
      align:'center'
    },
    {
      prop:'alertlevel',
      label:'警戒水位(米)',
      width:'',
      align:'center'
    },
    {
      prop:'Differ',
      label:'水位涨幅(米)',
      width:'',
      align:'center'
    }
  ],
  //山洪河流
  river:[
    {
      prop:'RIVER',
      label:'河流名称',
      width:'',
      align:'center'
    },
    {
      prop:'V06001',
      label:'经度',
      width:'',
      align:'center'
    },
    {
      prop:'V05001',
      label:'纬度',
      width:'',
      align:'center'
    },
    {
      prop:'DDATETIME',
      label:'预警时间',
      width:'',
      align:'center'
    },
    {
      prop:'WATERLEV',
      label:'当前水位(米)',
      width:'',
      align:'center'
    },
    {
      prop:'alertlevel(米)',
      label:'警戒水位',
      width:'',
      align:'center'
    },
    {
      prop:'Differ(米)',
      label:'水位涨幅',
      width:'',
      align:'center'
    }
  ],
  //内涝点
  waterloggingPoint: [
    {
      prop: 'name',
      label: '内涝点',
      width: '150',
      align:'center'
    },
    {
      prop: 'lat',
      label: '纬度',
      width: '120',
      align:'center',
    },
    {
      prop: 'lon',
      label: '经度',
      width: '120',
      align:'center'
    },
    {
      prop: 'manager',
      label: '负责人',
      width: '80',
      align:'center'
    },
    {
      prop: 'cellphone',
      label: '联系方式',
      width: '120',
      align:'center'
    },
    {
      prop: 'address',
      label: '地址',
      width: '250',
      align:''
    },
    {
      prop: 'detail',
      label: '详细',
      width: '',
      align:''
    },
  ],
  //内涝预警状态
  warningState: [
    {
      prop: 'name',
      label: '内涝点',
      width: '200',
      align:'center'
    },
    {
      prop:'lon',
      label:'经度',
      width:'100',
      align:'center'
    },
    {
      prop:'lat',
      label:'纬度',
      width:'100',
      align:'center'
    },
    {
      prop: 'ddatetime',
      label: '更新时间',
      width: '',
      align:'center'
    },
  ],
  //内涝预警报告
  warningReport: [
    {
      prop:'dataTime',
      label:'生成时间',
      width:'200',
      align:'center'
    },
    {
      prop:'fileName',
      label:'报告名称',
      width:'',
      align:'center'
    },
  ],
  //台风库
  typhoonInfo:[
    {
      prop:'tsid',
      label:'台风ID',
      width:'100',
      align:'center'
    },
    {
      prop:'name',
      label:'台风名称',
      width:'80',
      align:'center'
    },
    {
      prop:'level',
      label:'台风等级',
      width:'80',
      align:'center'
    },
    {
      prop:'landings',
      label:'登录地点',
      width:'80',
      align:'center'
    },
    {
      prop:'landingsLevel',
      label:'登录广东省强度',
      width:'120',
      align:'center'
    },
    {
      prop:'distance',
      label:'距站点(G2971)距离(公里)',
      width:'200',
      align:'center'
    },
    {
      prop:'landingsMonth',
      label:'登陆月份',
      width:'80',
      align:'center'
    },
    {
      prop:'maxWind',
      label:'自动站最大风力(m/s)',
      width:'',
      align:'center'
    },
    {
      prop:'maxRain',
      label:'自动站最大日雨量(mm)',
      width:'',
      align:'center'
    },
  ],
  //值班管理
  duty:[
      {
        prop:'dutydate',
        label:'值班日期',
        width:'',
        align:''
      },//值班日期
      {
        prop:'leader',
        label:'值班领导',
        width:'',
        align:''
      },//值班领导
       {
        prop:'cheif',
        label:'首席岗',
        width:'',
        align:''
      },//首席岗
       {
        prop:'captain_day',
        label:'白天领班',
        width:'',
        align:''
      },//白天领班
       {
        prop:'short_impending',
        label:'短临',
        width:'',
        align:''
      },//短临
    {
        prop:'audit',
        label:'审核',
        width:'',
        align:''
      },//审核
      {
        prop:'captain_night',
        label:'夜间领班',
        width:'',
        align:''
      },//夜间领班
      {
        prop:'emergency_day',
        label:'应急白班',
        width:'',
        align:''
      },//应急白班
       {
        prop:'cheif_service',
        label:'服务首席',
        width:'',
        align:''
      },//服务首席
       {
        prop:'onbusiness',
        label:'出差',
        width:'',
        align:''
      },//出差
       {
        prop:'vacation',
        label:'休假',
        width:'',
        align:''
      },//休假
       {
        prop:'vice_day',
        label:'白天副班',
        width:'',
        align:''
      },//白天副班
       {
        prop:'vice_night',
        label:'夜间副班',
        width:'',
        align:''
      },//夜间副班
      {
        prop:'office',
        label:'办公班',
        width:'',
        align:''
      },//办公班
       {
        prop:'consultation',
        label:'会商',
        width:'',
        align:''
      },//会商
      {
        prop:'remark',
        label:'备注',
        width:'',
        align:''
      }//备注
  ],
  //用户管理
  users:[
    {
      prop:'account',
      label:'账号',
      align:'center',
      width:''
    },
    {
      prop:'name',
      label:'用户名',
      align:'center',
      width:''
    },
    {
      prop:'nick',
      label:'姓名',
      align:'center',
      width:''
    },
    {
      prop:'phone',
      label:'手机号码',
      align:'center',
      width:''
    },
    {
      prop:'department',
      label:'部门',
      align:'center',
      width:''
    },
    {
      prop:'office',
      label:'科室',
      align:'center',
      width:''
    },
  ],
  //发布系统预警录入
  waringEntry:[
    {
      prop:'units',
      label:'单位',
      width:'80',
      align:'center',
    },
    {
      prop:'time',
      label:'录入时间',
      width:'150',
      align:'center',
    },
    {
      prop:'typeWarn',
      label:'事件类型',
      width:'120',
      align:'center',
    },
    {
      prop:'forecaster',
      label:'预报员',
      width:'80',
      align:'center',
    },
    {
      prop:'signer',
      label:'签发人',
      width:'80',
      align:'center',
    },
    {
      prop:'affirmNumber',
      label:'确认电话',
      width:'120',
      align:'center',
    },
    {
      prop:'smsGroup',
      label:'短信群',
      width:'100',
      align:'center',
    },
  /*  // {
    //   prop:'fax',
    //   label:'传真',
    //   width:'',
    //   align:'center',
    // },
    {
      prop:'web',
      label:'微博',
      width:'',
      align:'center',
    },
    {
      prop:'wechat',
      label:'微信',
      width:'',
      align:'center',
    },
    {
      prop:'pNote',
      label:'省突',
      width:'',
      align:'center',
    },
     {
       prop:'nNote',
       label:'本地短信',
       width:'',
       align:'center',
    },
     {
        prop:'website',
        label:'网站',
        width:'',
        align:'center',
    },
     {
       prop:'ftp',
       label:'FTP',
       width:'',
       align:'center',
    },
     {
       prop:'faxes',
       label:'传真',
       width:'',
       align:'center',
    },*/
    {
      prop:'noteMessage',
      label:'预警消息',
      width:'200',
      align:'',
    },
    {
      prop:'noteMessage',
      label:'备注消息',
      width:'200',
      align:'',
    },

    //  {
    //   prop:'defense',
    //   label:'国防',
    //   width:'',
    //    align:'center',
    // },
  ],
  //学校
  school:[
    {
      prop:'name',
      label:'学校名称',
      width:'250',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'120',
      align:'center',
    },
    {
      prop:'lon',
      label:'纬度',
      width:'120',
      align:'center',
    },
    {
      prop:'people',
      label:'学校人数',
      width:'120',
      align:'center',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'120',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'手机号',
      width:'120',
      align:'center',
    },
    {
      prop:'phone',
      label:'电话号码',
      width:'120',
      align:'center',
    },
    {
      prop:'address',
      label:'地址',
      width:'',
      align:'center',
    }
  ],
  //医院
  hospital:[
    {
      prop:'name',
      label:'医院/诊所名',
      width:'200',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'100',
      align:'center',
    },
    {
      prop:'lon',
      label:'经度',
      width:'100',
      align:'center',
    },
    {
      prop:'ambulance',
      label:'救护车数量',
      width:'100',
      align:'center',
    },
    {
      prop:'beds',
      label:'床位',
      width:'60',
      align:'center',
    },

    {
      prop:'doctor',
      label:'医生人数',
      width:'80',
      align:'center',
    },
    {
      prop:'nurse',
      label:'护士人数',
      width:'80',
      align:'center',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'120',
      align:'center',
    },
    {
      prop:'phone',
      label:'电话号码',
      width:'100',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'手机号',
      width:'120',
      align:'center',
    },
    {
      prop:'fax',
      label:'传真号',
      width:'100',
      align:'',
    },
    {
      prop:'address',
      label:'地址',
      width:'200',
      align:'center',
    },
  ],
  //危化品企业
  chemical:[
    {
      prop:'name',
      label:'危化品企业',
      width:'300',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'',
      align:'center',
    },
    {
      prop:'lon',
      label:'经度',
      width:'',
      align:'center',
    },
    {
      prop:'type',
      label:'类型',
      width:'120',
      align:'center',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'负责人电话',
      width:'120',
      align:'center',
    },
    {
      prop:'reporter',
      label:'填报人',
      width:'',
      align:'center',
      },
    {
      prop:'reporterphone',
      label:'填报人电话',
      width:'120',
      align:'center',
    },
    {
      prop:'address',
      label:'地址',
      width:'350',
      align:'center',
    },
  ],
  //避难所
  shelter:[
    {
      prop:'name',
      label:'避难所',
      width:'250',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'100',
      align:'center',
    },
    {
      prop:'lon',
      label:'经度',
      width:'100',
      align:'center',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'80',
      align:'center',
    },
    {
      prop:'managerphone',
      label:'负责人电话',
      width:'120',
      align:'center',
    },
    {
      prop:'managercellphone',
      label:'负责人手机号码',
      width:'120',
      align:'center',
    },
    {
      prop:'contact',
      label:'联系人',
      width:'80',
      align:'center',
    },
    {
      prop:'contactphone',
      label:'联系人电话',
      width:'120',
      align:'center',
    },
    {
      prop:'contactcellphone',
      label:'联系人手机号码',
      width:'120',
      align:'center',
    },
    {
      prop:'area',
      label:'占地面积(平方米)',
      width:'130',
      align:'center',
    },
    {
      prop:'people',
      label:'容纳人数',
      width:'80',
      align:'center',
    },
    {
      prop:'address',
      label:'地址',
      width:'400',
      align:'center',
    },
  ],
  //人口经济
  economy:[
    {
      prop:'name',
      label:'地名',
      width:'140',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'100',
      align:'center',
    },
    {
      prop:'lon',
      label:'经度',
      width:'100',
      align:'center',
    },
    {
      prop:'people',
      label:'总人口',
      width:'80',
      align:'center',
    },
    {
      prop:'gdp',
      label:'gdp指数',
      width:'80',
      align:'center',
    },
    {
      prop:'area',
      label:'占地面积(公顷)',
      width:'120',
      align:'center',
    },
    {
      prop:'plough',
      label:'耕地面积(公顷)',
      width:'120',
      align:'center',
    },
    {
      prop:'agriculture',
      label:'农业产值(万元)',
      width:'120',
      align:'center',
    },
    {
      prop:'aquaculture',
      label:'水产养殖面积(公顷)',
      width:'150',
      align:'center',
    },
    {
      prop:'industrial',
      label:'工业用电(千瓦/小时)',
      width:'150',
      align:'center',
    },
    {
      prop:'irrigationarea',
      label:'灌溉面积(公顷)',
      width:'130',
      align:'center',
    },
      {
        prop:'fruit',
        label:'林果种植面积(公顷)',
        width:'150',
        align:'center',
      },
  ],
  //专家库
  experts:[],
  //地址灾害
  geohazard:[],
//救援队伍
  rescueteam:[
    {
      prop:'name',
      label:'队伍名称',
      width:'250',
      align:'center',
    },
    {
      prop:'department',
      label:'所属部门',
      width:'250',
      align:'center',
    },
    {
      prop:'teamtype',
      label:'队伍类型',
      width:'250',
      align:'center',
    },
    {
      prop:'lat',
      label:'纬度',
      width:'250',
      align:'center',
    },
    {
      prop:'lon',
      label:'经度',
      width:'250',
      align:'center',
    },
    {
      prop:'people',
      label:'队伍人数',
      width:'100',
      align:'center',
    },
    {
      prop:'manager',
      label:'负责人',
      width:'250',
      align:'center',
    },
    {
      prop:'managercellphone',
      label:'负责人手机号',
      width:'250',
      align:'center',
    },
    {
      prop:'managerphone',
      label:'负责人电话',
      width:'150',
      align:'center'
    },
    {
      prop:'teamcontact',
      label:'联系人',
      width:'250',
      align:'center',
    },
    {
      prop:'contactcellphone',
      label:'联系人手机号',
      width:'250',
      align:'center',
    },
     {
      prop:'contactphone',
      label:'联系人电话',
      width:'250',
       align:'center',
    },
    {
      prop:'address',
      label:'地址',
      width:'250',
      align:'center',
    },
  ],
//救援物资
  material:[
     {
      prop:'name',
      label:'名称',
      width:'250',
       align:'center',
    },
     {
      prop:'lat',
      label:'纬度',
      width:'250',
       align:'center',
    },
     {
      prop:'lon',
      label:'经度',
      width:'250',
       align:'center',
    },
     {
      prop:'amount',
      label:'总额',
      width:'250',
       align:'center',
    },
    {
      prop:'contact',
      label:'联系人',
      width:'250',
      align:'center',
    },
    {
      prop:'contactcellphone',
      label:'联系人手机号',
      width:'250',
      align:'center',
    },
    {
      prop:'contactphone',
      label:'联系人电话',
      width:'250',
      align:'center',
    },
    {
      prop:'department',
      label:'所属部门',
      width:'250',
      align:'center',
    },
    {
      prop:'departmentphone',
      label:'部门电话',
      width:'250',
      align:'center',
    },
    {
      prop:'purpose',
      label:'用途',
      width:'250',
      align:'center',
    },
    {
      prop:'reporttime',
      label:'上报时间',
      width:'250',
      align:'center',
    },
    {
      prop:'unit',
      label:'单位',
      width:'250',
      align:'center',
    },
    {
      prop:'address',
      label:'地址',
      width:'250',
      align:'center',
    },
  ],
//通讯录
  mail:[
    {
      prop:'name',
      label:'姓名',
      width:'',
      align:'center',
    },
    {
      prop:'title',
      label:'职位',
      width:'',
      align:'center',
    },
    {
      prop:'department',
      label:'部门',
      width:'',
      align:'center',
    },
     {
      prop:'cellphone',
      label:'手机号码',
      width:'',
       align:'center',
    },
    {
      prop:'phone',
      label:'电话',
      width:'',
      align:'center',
    }
  ],
//预案录入
  PlansEntry:[
    {
      prop:'e_name',
      label:'预案类型',
      width:'150',
      align:'center',
    },
    {
      prop:'level',
      label:'预案等级',
      width:'',
      align:'center',
    },
    {
      prop:'department',
      label:'部门',
      width:'',
      align:'center',
    },
    {
      prop:'measure',
      label:'单位预案',
      width:'',
      align:'center',
    },
    {
      prop:'detail',
      label:'短信',
      width:'',
      align:'center',
    },
  ],
//历史预案
  HistoryPlan:[
    {
      prop:'emergencyname',
      label:'事件名称',
      width:'150',
      align:'center',
    },
    {
      prop:'emergencytype',
      label:'事件类型',
      width:'150',
      align:'center',
    },
    {
      prop:'responsegrade',
      label:'响应等级',
      width:'150',
      align:'center',
    },
    {
      prop:'unit',
      label:'成员单位',
      width:'150',
      align:'center',
    },
    {
      prop:'memo',
      label:'工作备忘',
      width:'',
      align:'center',
    },
  ],
//组织机构部门负责人
  InstiFrame:[
    {
      prop:'name',
      label:'姓名',
      width:'',
      align:'center',
    },
    {
      prop:'department',
      label:'部门',
      width:'',
      align:'center',
    },
    {
      prop:'position',
      label:'职位',
      width:'',
      align:'center',
    },
    {
      prop:'phone',
      label:'电话',
      width:'',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'手机号',
      width:'',
      align:'center',
    },
  ],
//专家库信息
  expertDatabase:[
     {
      prop:'name',
      label:'姓名',
      width:'',
       align:'center',
    },
    {
      prop:'department',
      label:'所属部门',
      width:'',
      align:'center',
    } ,
    {
      prop:'address',
      label:'居住地',
      width:'',
      align:'center',
    },
    {
      prop:'phone',
      label:'电话',
      width:'',
      align:'center',
    },
    {
      prop:'cellphone',
      label:'手机号',
      width:'',
      align:'center',
    }
  ],
//预案模板的事件类型
  PTAlertInfo:[
    {
      prop:'e_name',
      label:'预案名称',
      width:'',
      align:'center',
    },
    {
      prop:'starttip',
      label:'启动提示',
      width:'',
      align:'center',
    },
    {
      prop:'downtip',
      label:'降级提示',
      width:'',
      align:'center',
    },
    {
      prop:'uptip',
      label:'升级提示',
      width:'',
      align:'center',
    },
    {
      prop:'finishtip',
      label:'结束提示',
      width:'',
      align:'center',
    },
    {
      prop:'description',
      label:'描述',
      width:'',
      align:'center',
    },
  ],
//预案模板的工作备忘
  PTWorkingMemo: [
     {
      prop:'name',
      label:'备忘内容',
      width:'',
       align:'center',
    }
  ],
  //灾情审核
  disasterAudit:[
    {
      prop:'disaster',
      label:'灾情类型',
      width:'150',
      align:'center',
    },
    {
      prop:'remarks',
      label:'灾情内容',
      width:'250',
      align:'center',
    },
    {
      prop:'starttime',
      label:'灾情发生时间',
      width:'150',
      align:'center',
    },
    {
      prop:'economyLoss',
      label:'经济损失(万元)',
      width:'120',
      align:'center',
    },
    {
      prop:'injuryPerson',
      label:'死亡人数(人)',
      width:'120',
      align:'center',
    },
    {
      prop:'releaseUnit',
      label:'上报单位',
      width:'120',
      align:'center',
    },
    {
      prop:'reportMan',
      label:'上报人',
      width:'80',
      align:'center',
    },
  ],
  //历史灾情
  disasterHistory:[
    {
      prop:'disaster',
      label:'灾情类型',
      width:'150',
      align:'center',
    },
    {
      prop:'remarks',
      label:'灾情内容',
      width:'250',
      align:'center',
    },
    {
      prop:'starttime',
      label:'灾情发生时间',
      width:'150',
      align:'center',
    },
    {
      prop:'economyLoss',
      label:'经济损失(万元)',
      width:'120',
      align:'center',
    },
    {
      prop:'injuryPerson',
      label:'死亡人数(人)',
      width:'120',
      align:'center',
    },
    {
      prop:'releaseUnit',
      label:'上报单位',
      width:'120',
      align:'center',
    },
    {
      prop:'reportMan',
      label:'上报人',
      width:'80',
      align:'center',
    },
  ],
  //发布系统模板管理
  templateManage:[
    {
      prop:'id',
      label:'编号',
      width:'50',
      align:'center',
    },
    {
      prop:'forecaster',
      label:'预报员',
      width:'100',
      align:'center',
    },
    {
      prop:'signer',
      label:'签发人',
      width:'100',
      align:'center',
    },
    {
      prop:'affirmNumber',
      label:'确认数量',
      width:'100',
      align:'center',
    },
    {
      prop:'fax',
      label:'传真号',
      width:'150',
      align:'center',
    },
    {
      prop:'units',
      label:'发布单位',
      width:'150',
      align:'center',
    },
    {
      prop:'warnType',
      label:'预警类型',
      width:'100',
      align:'center',
    },

  ]
}
