export default {
  //内涝
  waterlogging:[
    {
      value:'waterloggingPoint',
      label:'内涝点',
    },
    {
      value:'warningState',
      label:'预警状态',
    },
    {
      value:'warningReport',
      label:'预警报告',
    },
  ],
  //台风
  typhoon:[
    {
      value:'typhoonInfo',
      label:'历史台风灾害库',
    },
    /*{
      value:'typhoonReport',
      label:'台风分析报告',
    },*/
  ],
  //山洪
  mountainTorrents:[
    {
      value:'mountainTorrentsPoint',
      label:'站点信息',
    },
    {
      value:'mountainTorrentsState',
      label:'预警状态',
    },
    {
      value:'mountainTorrentsReport',
      label:'预警报告',
    },
  ],
  //地质灾害
  geologicalDisaster:[
    {
      value:'geologicalDisasterPoint',
      label:'隐患点信息',
    },
    {
      value:'geologicalDisasterState',
      label:'预警状态',
    },
    {
      value:'geologicalDisasterReport',
      label:'预警报告',
    },
  ],
  //发布系统审核中心
  auditCenter:[
    {
      value:'toAudit',
      label:'待审核',
    },
    {
      value:'audited',
      label:'已审核',
    },
  ],
  //防灾救灾
  disasterRelief:[
    {
      value:'basicInfo',
      label:'基础信息',
    },
    {
      value:'rescueInfo',
      label:'救援信息',
    },
    {
      value:'addressBook',
      label:'通讯录',
    },
  ],
  //灾情服务管理
  disasterInformation:[
    {
      value:'zaiqinReport',
      label:'灾情上报',
    },
    {
      value:'zaiqinAudit',
      label:'灾情审核',
    },
    {
      value:'zaiqinHistory',
      label:'历史灾情',
    },
  ],
  //用户信息管理
  userInfoManage:[
    {
      value:'users',
      label:'用户管理',
    },
    // {
    //   value:'group',
    //   label:'应急群组',
    // },
    {
      value:'duty',
      label:'值班管理',
    },
  ],
  //应急预案管理
  contingencyPlan:[
    {
      value:'PlansEntry',
      label:'预案录入',
    },
    {
      value:'HistoryPlans',
      label:'历史预案',
    },
    {
      value:'PlansTemplate',
      label:'预案模板',
    },
    {
      value:'expertDatabase',
      label:'应急专家',
    },
    {
      value:'InstiFrame',
      label:'应急机构',
    },

  ]
}
